[book]
authors = ["mdbook-plugins"]
language = "zh"
src = "src"
title = "mdbook-plugins 文档"
description = "mdbook-plugins 是一个单二进制文件，捆绑了 20 个 mdbook 插件（预处理器和渲染器），通过命令路由进行分发。"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "navy"
mathjax-support = true

[build]
build-dir = "books"
create-missing = true
use-default-preprocessors = false
# extra-watch-dirs = ["po"]